version: '3.8'

services:
  postgresdb:
    container_name: postgresdb
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=demo
    volumes:
      - postgres_datastore:/var/lib/postgresql/data

volumes:
  postgres_datastore: